# Generated by Django 4.2.6 on 2023-12-27 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('sName', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('sLocation', models.CharField(max_length=100)),
                ('Principal', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('uName', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('uLocation', models.CharField(max_length=100)),
                ('Principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.school')),
            ],
        ),
    ]
